In [2]:
# Import Dataset For MINST
import pandas as pd
import numpy as np
# SRC: https://www.kaggle.com/code/wwsalmon/simple-mnist-nn-from-scratch-numpy-no-tf-keras

In [10]:
## Explore The Data
data = pd.read_csv("./mnist_train.csv")
data.head(3)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [48]:
data = np.array(data)
m, n = data.shape # get number of rows and number of element in 2D array
# np.random.shuffle(data) # WHY THIS

data_dev = data[0: 1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1: m]

data_train = data[1000: m].T
X_train = data_train[1: n]
Y_train = data_train[0]

In [49]:
X_train.shape # (NLine, NColumn)

(784, 9000)

In [50]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# Init The Hyper Parameter
nbr_neural_hidden_layer = 10
def init_param():
    # n is number of columns in dataset
    W_1 = np.random.rand(10, 784) - 0.5
    B_1 = np.random.rand(10, 1) - 0.5

    W_2 = np.random.rand(10, 10) - 0.5
    B_2 = np.random.rand(10, 1) - 0.5
    return W_1, B_1, W_2, B_2
init_param()

# ForWard Propagation
def ReLU(Z):
    return np.where(Z > 0, 1, 0)

def softMaX(Z):
    return np.exp(Z) - np.sum(np.exp(Z))

W_1, B_1, W_2, B_2 = init_param()
def forward_prop(W_1, B_1, W_2, B_2, X):
    # Calculate Z_1 = W_1 * A_0 + B_1
    global A_1, Z_1
    Z_1 = W_1.dot(X) + B_1
    A_1 = ReLU(Z_1)
    print("W_1 shape:", W_1.shape)
    print("B_1 shape:", B_1.shape)
    print("Z_1 shape:", Z_1.shape)
    print("A_1 shape:", A_1.shape)
    
    # Calculate Z_2 = W_2 * A_1 + B_2
    global A_2, Z_2
    Z_2 = W_2.dot(A_1) + B_2
    A_2 = softMaX(Z_2)
    print("W_2 shape:", W_2.shape)
    print("A_1 shape:", A_1.shape)
    print("Z_2 shape:", Z_2.shape)
    print("A_2 shape:", A_2.shape)

forward_prop(W_1, B_1, W_2, B_2, X_train)

# BackWard Propagation
def on_hot_code(Y):
    Y_len = len(Y)
    new_Y = np.zeros(shape=(10, Y_len), dtype=np.uint8)
    
    # print(Y)
    for i in range(Y_len):
        new_Y[Y[i]][i] = 1
    # print(new_Y)
    return new_Y

def ReLU_deriv(Z):
    return Z > 0

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    Y_new = on_hot_code(Y)
    print("A_2 Shape: ", A_2.shape)
    print("Y_new Shape: ", Y_new.shape)
    
    ### FOR OUTPUR LAYER
    dZ_2 = A_2 - Y
    dW_2 = (1/m) * dZ_2.dot(A_1.T)
    dB_2 = (1/m) * np.sum(dZ_2)
    
    ### FOR HIDDEN LAYER
    dZ_1 = W_2.T.dot(dZ_2) * ReLU_deriv(Z_1)
    dW_1 = (1/m) * dZ_1.dot(X.T) # where A_0 is X
    dB_1 = (1/m) * np.sum(dZ_1)
    
    return dZ_2, dW_2, dB_2, dZ_1, dW_1, dB_1


# Update Params
def update_params(W_1, W_2, B_1, B_2, dW_1, dW_2, dB_1, dB_2, alpha):
    W_2 = W_2 - alpha * dW_2
    B_2 = B_2 - alpha * dB_2
    W_1 = W_1 - alpha * dW_1
    B_1 = B_1 - alpha * dB_1

W_1 shape: (10, 784)
B_1 shape: (10, 1)
Z_1 shape: (10, 9000)
A_1 shape: (10, 9000)
W_2 shape: (10, 10)
A_1 shape: (10, 9000)
Z_2 shape: (10, 9000)
A_2 shape: (10, 9000)


In [5]:
# Forward Propagation
w = []
nbr_layer = 4
nbr_neural_hidden_layer = 10
nbr_neural_input_layer = 16
X = np.array(range(0, nbr_neural_input_layer))

# Calculate the Z[1] = A[0] * W[1] + b Where A[1] = X
A_0 = X
W_1 = np.arange(nbr_neural_input_layer * nbr_neural_hidden_layer).reshape(nbr_neural_input_layer, nbr_neural_hidden_layer)
B_1 = np.array(range(0, nbr_neural_hidden_layer))
Z_1 = np.dot(A_0, W_1) + B_1
## Relu Function in Hidden Layer #1 Neurons
A_1 = np.where(Z_1 > 0, 1, 0)

# Calculate Z_2 = A_1 * W_2 + B_2
W_2 = np.arange(nbr_neural_hidden_layer * nbr_neural_hidden_layer).reshape(nbr_neural_hidden_layer, nbr_neural_hidden_layer)
B_2 = np.array(range(0, nbr_neural_hidden_layer))
Z_2 = np.dot(A_1, W_2) + B_2

## Sigmoid Function in Hidden Layer #2 Neurons 
A_2 = 1 - (1 - np.exp(-Z_2))
A_2

# Calculate The y_estimated
W_3 = np.arange(nbr_neural_hidden_layer * 1).reshape(nbr_neural_hidden_layer, 1)
B_3 = np.array(range(0, 1))
Y = np.dot(A_2, W_3) + B_3
Y

array([0.])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])